### ISSUE TITLE
Panduan Install di Mac OS

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/docs#19]
## Goal

Mengisi konten halaman https://bukumasjid.com/docs/installation/mac/.
Mengisinya di sini https://github.com/buku-masjid/docs/blob/master/content/id/docs/installation/mac.md.
Contoh isi konten: https://bukumasjid.com/docs/installation/ubuntu-linux-mint/

## Checklist

- [x] Panduan install localhost Mac OS

**Comment by budimanfajarf** [comment]
Halo Mas @nafiesl, panduan install di Mac OS ini mau jalaninnya pakai `php artisan serve` atau pakai `valet` Mas? 

Kalau pakai `php artisan serve`, saya coba di mac ngikutin panduan yg [ubuntu-linux-mint](https://bukumasjid.com/docs/installation/ubuntu-linux-mint/) itu berjalan dengan baik Mas (php yg saya gunakan versi 8.1)

Atau mau pakai `valet` Mas? Kalau pakai valet kelebihannya dipanduannya nanti bisa nambahin step `valet use php@8.1` buat mastiin versi php yg dijalanin itu compatible buat buku-masjid ini

**Comment by nafiesl** [comment]
Halo mas @budimanfajarf, alhamdulillah. Kalau begitu pakai valet saja mas, kemungkinan pengguna Mac OS lebih banyak yang valet dibandingkan artisan serve. Tetapi bisa ditambahkan juga di awal panduan bahwa jika tanpa laravel valet, bisa ikut panduan yang ubuntu linux mint.


Terima kasih mas.

**Comment by budimanfajarf** [comment]
Oke noted, terima kasih Mas. Saya ijin contribute untuk task ini kalo begitu ya.

**Comment by nafiesl** [comment]
### Progress saat ini 

1. @budimanfajarf kontribusi PR https://github.com/buku-masjid/docs/pull/25
2. @nafiesl review https://github.com/buku-masjid/docs/pull/25#pullrequestreview-1640913409

### Selanjutnya

1. @budimanfajarf update PR sesuai review @nafiesl

**Comment by nafiesl** [comment]
### Progress saat ini

1. PR #25 sudah merge
2. @budimanfajarf submit PR https://github.com/buku-masjid/docs/pull/26 untuk improvement, sudah merge juga.

Makasih banyak mas @budimanfajarf, ditunggu kontribusi lainnya mas :pray:
