### ISSUE TITLE
Kekurangan Langkah Install pada Panduan Cara Deploy VPS Ubuntu Server (Apache)

### ISSUE THREAD

**Issue by nafiesl** [buku-masjid/docs#63]
## Deskripsi

Pada task ini kita ingin menambahkan kekurangan langkah [deploy buku masjid di VPS Ubuntu Server](https://bukumasjid.com/docs/deployment/vps-ubuntu-server). Sekaligus menambahkan link youtube tutorial video dari mas @musaamin: https://www.youtube.com/watch?v=EBgldM3Erus

## Checklist

- [x] Tambahkan langkah menjalankan perintah `php artisan key:generate` setelah langkah `Copy file .env` pada halaman panduan https://bukumasjid.com/docs/deployment/vps-ubuntu-server
- [x] Tambahkan video youtube https://www.youtube.com/watch?v=JYfRzlYLgM8 bagian paling atas sebagai tutorial video deploy buku masjid pada VPS.

**Comment by nafiesl** [comment]
###  Progress

Kekurangan langkah installnya sudah ditambahkan oleh mas @musaamin di PR #64.

### Selanjutnya

Mas Musa Amin rencana mau buat ulang video tutorialnya, jika sudah ada video terbaru, kita muat di halaman panduan ini.

**Comment by musaamin** [comment]
Video yang baru di https://www.youtube.com/watch?v=JYfRzlYLgM8
Perlu juga ditambahkan perintah membuka file .env `nano .env`

**Comment by nafiesl** [comment]
Alhamdulillah, siap mas @musaamin saya tambahkan video di halamannya.

**Comment by nafiesl** [comment]
### Progress

1. Saya coba tambahkan video youtube, tetapi terkendala error Content Security Policy (screenshot terlampir)
2. Coba update header untuk tambah URL, tapi belum berhasil ([05dcd5a](https://github.com/buku-masjid/docs/commit/05dcd5a7c2b541d035d3024275b9de66c5ced1d7)).

Screenshot

![screen_2024-09-04_012](https://github.com/user-attachments/assets/5dcb30d8-e8c4-4b42-8b26-40f89278d673)

### Next TODO

1. Masih mencari solusi lain agar video youtube bisa dimainkan di web (secara embed).
2. Jika tidak bisa, mungkin diberikan link ke video youtubenya saja.

**Comment by nafiesl** [comment]
### Progress

1. Alhamdulillah sudah berhasil memasang youtube video pada halaman artikel secara embed setelah ditambahkan content security policy ([73b13ae](https://github.com/buku-masjid/docs/commit/73b13ae9f67e35950bcf526438ebe88ad69a0fe5))

Link Panduan:
https://bukumasjid.com/docs/deployment/vps-ubuntu-server/#install-mariadb

Screenshot:

![screen_2024-09-05_001](https://github.com/user-attachments/assets/e1e8acb3-a637-4132-92d5-b223159220d6)


Issue ini bisa kita close. Sekali lagi terima kasih kontribusinya mas @musaamin.
